export const CART_SERVICE = 'CART_SERVICE';
export const PRODUCT_SERVICE = 'PRODUCT_SERVICE';
export const COUPON_SERVICE = 'COUPON_SERVICE';
export const USER_SERVICE = 'USER_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';